language: python

python:
    - 2.6
    - 2.7
    - 3.2
    - 3.3

env:
    global:
        - PIP_WHEEL_COMMAND="pip install --find-links http://wheels.astropy.org/ --use-wheel --use-mirrors"


before_install:
    - pip install setuptools --upgrade
    - pip install pip --upgrade
    - pip install wheel

install:
   - $PIP_WHEEL_COMMAND "numpy==1.8.0"
   - $PIP_WHEEL_COMMAND "astropy==0.3"
   - $PIP_WHEEL_COMMAND "Cython==0.19"

script:
   - python setup.py test
